# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AbWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(592, 471)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(414, 410))
        self.a0slid = QtWidgets.QSlider(Form)
        self.a0slid.setGeometry(QtCore.QRect(218, 44, 141, 31))
        self.a0slid.setMinimum(-100)
        self.a0slid.setMaximum(100)
        self.a0slid.setSingleStep(1)
        self.a0slid.setProperty("value", 3)
        self.a0slid.setSliderPosition(3)
        self.a0slid.setOrientation(QtCore.Qt.Horizontal)
        self.a0slid.setInvertedAppearance(False)
        self.a0slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a0slid.setTickInterval(20)
        self.a0slid.setObjectName("a0slid")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(31, 51, 81, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(31, 85, 67, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(31, 119, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(31, 153, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(31, 187, 151, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(31, 255, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(31, 289, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(31, 221, 161, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(31, 323, 101, 16))
        self.label_10.setObjectName("label_10")
        self.a1slid = QtWidgets.QSlider(Form)
        self.a1slid.setGeometry(QtCore.QRect(218, 78, 141, 31))
        self.a1slid.setMinimum(-100)
        self.a1slid.setMaximum(100)
        self.a1slid.setSingleStep(1)
        self.a1slid.setOrientation(QtCore.Qt.Horizontal)
        self.a1slid.setInvertedAppearance(False)
        self.a1slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a1slid.setTickInterval(20)
        self.a1slid.setObjectName("a1slid")
        self.a2slid = QtWidgets.QSlider(Form)
        self.a2slid.setGeometry(QtCore.QRect(218, 116, 141, 27))
        self.a2slid.setMinimum(-100)
        self.a2slid.setMaximum(100)
        self.a2slid.setSingleStep(1)
        self.a2slid.setOrientation(QtCore.Qt.Horizontal)
        self.a2slid.setInvertedAppearance(False)
        self.a2slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a2slid.setTickInterval(20)
        self.a2slid.setObjectName("a2slid")
        self.a3slid = QtWidgets.QSlider(Form)
        self.a3slid.setGeometry(QtCore.QRect(218, 150, 141, 27))
        self.a3slid.setMinimum(-100)
        self.a3slid.setMaximum(100)
        self.a3slid.setSingleStep(1)
        self.a3slid.setOrientation(QtCore.Qt.Horizontal)
        self.a3slid.setInvertedAppearance(False)
        self.a3slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a3slid.setTickInterval(20)
        self.a3slid.setObjectName("a3slid")
        self.a4slid = QtWidgets.QSlider(Form)
        self.a4slid.setGeometry(QtCore.QRect(218, 184, 141, 27))
        self.a4slid.setMinimum(-100)
        self.a4slid.setMaximum(100)
        self.a4slid.setSingleStep(1)
        self.a4slid.setOrientation(QtCore.Qt.Horizontal)
        self.a4slid.setInvertedAppearance(False)
        self.a4slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a4slid.setTickInterval(20)
        self.a4slid.setObjectName("a4slid")
        self.a5slid = QtWidgets.QSlider(Form)
        self.a5slid.setGeometry(QtCore.QRect(218, 218, 141, 27))
        self.a5slid.setMinimum(-100)
        self.a5slid.setMaximum(100)
        self.a5slid.setSingleStep(1)
        self.a5slid.setOrientation(QtCore.Qt.Horizontal)
        self.a5slid.setInvertedAppearance(False)
        self.a5slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a5slid.setTickInterval(20)
        self.a5slid.setObjectName("a5slid")
        self.a6slid = QtWidgets.QSlider(Form)
        self.a6slid.setGeometry(QtCore.QRect(218, 252, 141, 27))
        self.a6slid.setMinimum(-100)
        self.a6slid.setMaximum(100)
        self.a6slid.setSingleStep(1)
        self.a6slid.setOrientation(QtCore.Qt.Horizontal)
        self.a6slid.setInvertedAppearance(False)
        self.a6slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a6slid.setTickInterval(20)
        self.a6slid.setObjectName("a6slid")
        self.a7slid = QtWidgets.QSlider(Form)
        self.a7slid.setGeometry(QtCore.QRect(218, 287, 141, 31))
        self.a7slid.setMinimum(-100)
        self.a7slid.setMaximum(100)
        self.a7slid.setSingleStep(1)
        self.a7slid.setOrientation(QtCore.Qt.Horizontal)
        self.a7slid.setInvertedAppearance(False)
        self.a7slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a7slid.setTickInterval(20)
        self.a7slid.setObjectName("a7slid")
        self.a8slid = QtWidgets.QSlider(Form)
        self.a8slid.setGeometry(QtCore.QRect(218, 320, 141, 27))
        self.a8slid.setMinimum(-100)
        self.a8slid.setMaximum(100)
        self.a8slid.setSingleStep(1)
        self.a8slid.setOrientation(QtCore.Qt.Horizontal)
        self.a8slid.setInvertedAppearance(False)
        self.a8slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.a8slid.setTickInterval(20)
        self.a8slid.setObjectName("a8slid")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(30, 10, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.a0 = QtWidgets.QDoubleSpinBox(Form)
        self.a0.setGeometry(QtCore.QRect(370, 40, 41, 24))
        self.a0.setReadOnly(True)
        self.a0.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a0.setMinimum(-3.14)
        self.a0.setMaximum(3.14)
        self.a0.setSingleStep(0.01)
        self.a0.setObjectName("a0")
        self.a1 = QtWidgets.QDoubleSpinBox(Form)
        self.a1.setGeometry(QtCore.QRect(370, 80, 41, 24))
        self.a1.setReadOnly(True)
        self.a1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a1.setMinimum(-3.14)
        self.a1.setMaximum(3.14)
        self.a1.setSingleStep(0.01)
        self.a1.setObjectName("a1")
        self.a2 = QtWidgets.QDoubleSpinBox(Form)
        self.a2.setGeometry(QtCore.QRect(370, 120, 41, 24))
        self.a2.setReadOnly(True)
        self.a2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a2.setMinimum(-3.14)
        self.a2.setMaximum(3.14)
        self.a2.setSingleStep(0.01)
        self.a2.setObjectName("a2")
        self.a3 = QtWidgets.QDoubleSpinBox(Form)
        self.a3.setGeometry(QtCore.QRect(370, 150, 41, 24))
        self.a3.setReadOnly(True)
        self.a3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a3.setMinimum(-3.14)
        self.a3.setMaximum(3.14)
        self.a3.setSingleStep(0.01)
        self.a3.setObjectName("a3")
        self.a4 = QtWidgets.QDoubleSpinBox(Form)
        self.a4.setGeometry(QtCore.QRect(370, 180, 41, 24))
        self.a4.setReadOnly(True)
        self.a4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a4.setMinimum(-3.14)
        self.a4.setMaximum(3.14)
        self.a4.setSingleStep(0.01)
        self.a4.setObjectName("a4")
        self.a5 = QtWidgets.QDoubleSpinBox(Form)
        self.a5.setGeometry(QtCore.QRect(370, 220, 41, 24))
        self.a5.setReadOnly(True)
        self.a5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a5.setMinimum(-3.14)
        self.a5.setMaximum(3.14)
        self.a5.setSingleStep(0.01)
        self.a5.setObjectName("a5")
        self.a6 = QtWidgets.QDoubleSpinBox(Form)
        self.a6.setGeometry(QtCore.QRect(370, 250, 41, 24))
        self.a6.setReadOnly(True)
        self.a6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a6.setMinimum(-3.14)
        self.a6.setMaximum(3.14)
        self.a6.setSingleStep(0.01)
        self.a6.setObjectName("a6")
        self.a7 = QtWidgets.QDoubleSpinBox(Form)
        self.a7.setGeometry(QtCore.QRect(370, 290, 41, 24))
        self.a7.setReadOnly(True)
        self.a7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a7.setMinimum(-3.14)
        self.a7.setMaximum(3.14)
        self.a7.setSingleStep(0.01)
        self.a7.setObjectName("a7")
        self.a8 = QtWidgets.QDoubleSpinBox(Form)
        self.a8.setGeometry(QtCore.QRect(370, 320, 41, 24))
        self.a8.setReadOnly(True)
        self.a8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.a8.setMinimum(-3.14)
        self.a8.setMaximum(3.14)
        self.a8.setSingleStep(0.01)
        self.a8.setObjectName("a8")
        self.Reset = QtWidgets.QPushButton(Form)
        self.Reset.setGeometry(QtCore.QRect(40, 350, 113, 32))
        self.Reset.setObjectName("Reset")
        self.randomslider = QtWidgets.QSlider(Form)
        self.randomslider.setGeometry(QtCore.QRect(230, 390, 160, 22))
        self.randomslider.setMaximum(200)
        self.randomslider.setOrientation(QtCore.Qt.Horizontal)
        self.randomslider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.randomslider.setTickInterval(20)
        self.randomslider.setObjectName("randomslider")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(109, 390, 101, 20))
        self.label_2.setObjectName("label_2")
        self.optimize = QtWidgets.QPushButton(Form)
        self.optimize.setGeometry(QtCore.QRect(40, 430, 113, 32))
        self.optimize.setObjectName("optimize")
        self.unoptimize = QtWidgets.QPushButton(Form)
        self.unoptimize.setGeometry(QtCore.QRect(180, 430, 113, 32))
        self.unoptimize.setObjectName("unoptimize")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Piston (A_0)"))
        self.label_3.setText(_translate("Form", "X-Tilt (A_1)"))
        self.label_4.setText(_translate("Form", "Y-Tilt (A_2)"))
        self.label_5.setText(_translate("Form", "Defocus (A_3)"))
        self.label_6.setText(_translate("Form", "0 Deg Astigmatism (A_4)"))
        self.label_7.setText(_translate("Form", "X-Coma (A_6)"))
        self.label_8.setText(_translate("Form", "Y-Coma (A_7)"))
        self.label_9.setText(_translate("Form", "45 Deg Astigmatism (A_5)"))
        self.label_10.setText(_translate("Form", "Spherical (A_8)"))
        self.label_19.setText(_translate("Form", "Abberation Correction"))
        self.Reset.setText(_translate("Form", "Reset"))
        self.label_2.setText(_translate("Form", "Random (0,2pi)"))
        self.optimize.setText(_translate("Form", "OPTIMIZE!!"))
        self.unoptimize.setText(_translate("Form", "de-optimize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

